Add tutorial debugging with protostar
starknet-edu/walking-with-starknet pull request #25
Opened 2022-10-27 02:43 UTC by dpinones

2022-10-28 00:34 UTC, dimeyad requested changes
Solo cambié unos detalles

2022-11-02 11:07 UTC, omarespejel requested changes
Muchisimas gracias @dpinones por la gran aportación! Un tema muy importante. También gracias @dimeyad por el review previo!

Agrego algo de feedback que es más en cuando a redacción de algunas cosas y mantener el formato de los tutoriales de walking with starknet.

Cualquier duda no dudes en decirme!

2022-11-02 11:07 UTC, omarespejel commented on tutorials/tutorials/ES/6_debugging_con_protostar.md
> +Tenemos un contrato y sus respectivos tests. Además tenemos el server.
por favor cuando se pase el contrato y los tests, podemos poner links a esos archivos aquí mismo. Por ejemplo, sería algo como "Usaremos el contrato [testing.cairo](.../.../src/testing.cairo) y los sus tests en [test_testing.cairo](...)". Obvio ya con los nombres de archivo que consideres adecuados.

También sería bueno si pudieras porfa detallar un poco más a qué te refieres con "server" para que los estudiantes entiendan un poco más. Es un tema que no hemos tocado aún en estos tutoriales.

2022-11-02 11:07 UTC, omarespejel commented on tutorials/tutorials/ES/6_debugging_con_protostar.md
> +## 4. Contrato main
Quizás el nombre del contrato tendría que cambiar si lo subimos a los contratos de walking with starknet.

2022-11-02 11:07 UTC, omarespejel commented on tutorials/tutorials/ES/6_debugging_con_protostar.md
> +El contrato main tiene una `@storage_var` llamada balance. También tiene la función llamada `get_balance` que retorna el balance actual y también tiene la función llamada `increase_balance` para aume
```suggestion
El contrato (XXX: por favor agregar link al contrato dentro de walking with starknet) tiene:
* La variable de storage `balance`.  
* La función `get_balance()`: retorna el balance actual. 
* La función `increase_balance()` para aumentar el balance. El balance inicia en 0.
```

2022-11-02 11:15 UTC, omarespejel requested changes

2022-11-02 11:15 UTC, omarespejel commented on tutorials/tutorials/ES/6_debugging_con_protostar.md
> +Test de la función `increase_balance`.
Sería bueno por ejemplo agregar snippets del código (no en imágenes sino snippets pegados) e indicando lo que se hace en los tests. Es decir, explica la carnita de lo que estamos haciendo.

2022-11-02 11:15 UTC, omarespejel commented on tutorials/tutorials/ES/6_debugging_con_protostar.md
> +Twitter: https://twitter.com/dpinoness
No solemos agregar los datos de contacto de las personas que contribuyen con los tutoriales. Es para hacerlo estilo open-source. Igual tu contacto queda en la tabla de contribuidores en el `README.md`.

2022-11-02 11:15 UTC, omarespejel commented on tutorials/tutorials/ES/6_debugging_con_protostar.md
> +La gran mayoría de veces no es necesario hacer el debugging de esta manera. Haciendo un test para una función particular y los assert correctos ya alcanzaría. Pero en una experiencia reciente teníamo
```suggestion
La gran mayoría de veces no es necesario hacer el debugging de esta manera. Haciendo un test para una función particular y los assert correctos ya alcanzaría. Sin embargo, si se busca hacer seguimiento a un algoritmo complejo puede ser de mucha utilidad. Al tener muchas funciones, muchas líneas de código y muchos llamados recursivos se pueden perder los detalles del funcionamiento.
```

Quito un poco la parte muy particular a la experiencia individual.

2023-07-23 12:27 UTC, closed without merging